### ISSUE TITLE
AssertionError: Tried to stop a LoopingCall that was not running.

### ISSUE THREAD

**Issue by tonal** [twisted/txmongo#259] opened 2019-10-22 04:29 UTC
Log:
```
...
2019-10-21 23:14:17,223 [twisted] CRITICAL:
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.6.9/envs/amon/lib/python3.6/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/opt/pyenv/versions/3.6.9/envs/amon/lib/python3.6/site-packages/txmongo/connection.py", line 424, in __discovery_nodes_to_ping
    del self.__pingers[unused_peer]
KeyError: IPv4Address(type='TCP', host='XXX.XXX.XXX.XXX', port=27017)
...
...
2019-10-21 23:16:31,743 [scrapy.core.engine] INFO: Closing spider (finished)
2019-10-21 23:16:31,743 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method MongoExtension.spider_closed of <amon.mongo_ext.MongoExtension object at 0x7fac7b2ff208>>
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.6.9/envs/amon/lib/python3.6/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/opt/pyenv/versions/3.6.9/envs/amon/lib/python3.6/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/opt/amon/amon/amon/mongo_ext.py", line 102, in spider_closed
    return disconnect()
  File "/opt/pyenv/versions/3.6.9/envs/amon/lib/python3.6/site-packages/txmongo/connection.py", line 346, in disconnect
    self.__pinger_discovery.stop()
  File "/opt/pyenv/versions/3.6.9/envs/amon/lib/python3.6/site-packages/twisted/internet/task.py", line 202, in stop
    assert self.running, ("Tried to stop a LoopingCall that was "
AssertionError: Tried to stop a LoopingCall that was not running.
...
```
I hide real host.

**Comment by IlyaSkriblovsky** [comment] 2019-10-22 07:06
Thanks for the finding. I think the fix is pretty trivial, see #260.

**Comment by sekogan** [comment] 2020-05-14 15:10
Also ran into this issue.

@IlyaSkriblovsky Not sure #260 fixed it, let me explain why:

1. The idea of the fix (correct me if I got it wrong) is that if the LoopingCall was created and stopped in less than 10 seconds it could cause an assertion error. But in my case the LoopingCall was created many hours before the assertion failure.

2. A LoopingCall stops itself if its callback raises an exception. The logs provided by the issue reporter show that it's probably the case here. The function `__discovery_nodes_to_ping` is passed to the LoopingCall as a callback. When that callback raised a KeyError the LoopingCall shut itself down.

**Comment by IlyaSkriblovsky** [comment] 2020-05-15 08:35
@sekogan, you are right, #260 fixed only "LoopingCall that was not running" exception, but not the root cause: "KeyError: IPv4Address(...)".

Seems like `disconnect()` call can immediately call `__on_ping_lost/__on_ping_fail` which will delete pinger from `__pingers`. So `del` on the next line fails with `KeyError`.

```python
        for unused_peer in existing - peers:
            self.__pingers[unused_peer].connector.disconnect()
            del self.__pingers[unused_peer]
```

So we probably might use `.pop(key, None)` instead of `del` here because we just want to be sure `unused_peer` is not in `__pingers` anymore.

**Closed** 2020-08-24 19:57 UTC
